{
 "title": "Borg Backup status",
 "description": "Status of borg backup",
 "tags": [
  "backup",
  "borg"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backupserver",
    "label": "Backup server",
    "query": "label_values(borg_archives_count, backupserver)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(borg_archives_count, host)"
   }
  ]
 },
 "panels": [
  { "title": "Backup server stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total repos",
   "type": "stat",
   "description": "Number of repos on server",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (borg_archives_count{backupserver=\"$backupserver\"}))"
    }
   ]
  },
  {
   "title": "Total archives",
   "type": "stat",
   "description": "Number of archives in all repos",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_archives_count{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Uncompressed size",
   "type": "stat",
   "description": "Size of all the data, uncompressed",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_total_size{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Compressed size",
   "type": "stat",
   "description": "Size of all the data, compressed",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_total_size_compressed{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Deduplicated size",
   "type": "stat",
   "description": "Size of all the data, compressed and deduplicated",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_total_size_dedup{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Disk saving %",
   "type": "gauge",
   "description": "How much space you are saving with compression and deduplication",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-sum(borg_total_size_dedup{backupserver=\"$backupserver\"})/sum(borg_total_size{backupserver=\"$backupserver\"})*100"
    }
   ]
  },
  {
   "title": "Backup server stats (today's backups)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Total repos",
   "type": "stat",
   "description": "Number of repos on server",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (borg_archives_count_today{backupserver=\"$backupserver\"} >0))"
    }
   ]
  },
  {
   "title": "Total archives",
   "type": "stat",
   "description": "Number of archives in all repos",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_archives_count_today{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Uncompressed size",
   "type": "stat",
   "description": "Size of all the data, uncompressed",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_last_size{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Compressed size",
   "type": "stat",
   "description": "Size of all the data, compressed",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_last_size_compressed{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Deduplicated size",
   "type": "stat",
   "description": "Size of all the data, compressed and deduplicated",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_last_size_dedup{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Disk saving %",
   "type": "gauge",
   "description": "How much space you are saving with compression and deduplication",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-sum(borg_last_size_dedup{backupserver=\"$backupserver\"})/sum(borg_last_size{backupserver=\"$backupserver\"})*100"
    }
   ]
  },
  {
   "title": "Files archived",
   "type": "stat",
   "description": "Number of files in all repos",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_files_count{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Total chunks",
   "type": "stat",
   "description": "Number of chunks in all repos",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_chunks_total{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Unique chunks",
   "type": "stat",
   "description": "Number of unique chunks in all repos",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_chunks_unique{backupserver=\"$backupserver\"})"
    }
   ]
  },
  {
   "title": "Unique chunk %",
   "type": "gauge",
   "description": "Percentage of unique chunks",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_chunks_unique{backupserver=\"$backupserver\"})/sum(borg_chunks_total{backupserver=\"$backupserver\"})*100"
    }
   ]
  },
  { "title": "Backup details for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "host" },
  {
   "title": "Total archives",
   "type": "stat",
   "description": "Number of archives in the selected repo",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_archives_count{backupserver=\"$backupserver\", host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Today archives",
   "type": "stat",
   "description": "Number of archives saved today",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_archives_count_today{backupserver=\"$backupserver\", host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Uncompressed size",
   "type": "stat",
   "description": "Size of all the data, uncompressed",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_last_size{backupserver=\"$backupserver\", host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Compressed size",
   "type": "stat",
   "description": "Size of all the data, compressed",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_last_size_compressed{backupserver=\"$backupserver\", host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Deduplicated size",
   "type": "stat",
   "description": "Size of all the data, compressed and deduplicated",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(borg_last_size_dedup{backupserver=\"$backupserver\", host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Disk saving %",
   "type": "gauge",
   "description": "How much space you are saving with compression and deduplication",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-sum(borg_last_size_dedup{backupserver=\"$backupserver\", host=\"$host\"})/sum(borg_last_size{backupserver=\"$backupserver\", host=\"$host\"})*100"
    }
   ]
  },
  {
   "title": "Original sizes",
   "type": "bargauge",
   "description": "Breakdown per archive",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "borg_last_size{backupserver=\"$backupserver\", host=\"$host\"}",
     "legendFormat": "{{archive}}"
    }
   ]
  },
  {
   "title": "Deduplicated sizes",
   "type": "bargauge",
   "description": "Breakdown per archive",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "borg_last_size_dedup{backupserver=\"$backupserver\", host=\"$host\"}",
     "legendFormat": "{{archive}}"
    }
   ]
  }
 ]
}